Feature --> Develop
DevOpsMentorship/terraform_vpc pull request #1
Opened 2021-07-30 10:42 UTC by tkachuk09

2021-08-04 14:06 UTC, kteneta requested changes

2021-08-04 14:26 UTC, tkachuk09 commented on provider.tf
> +      shared_credentials_file = "/vlad/.aws/credentials"
got it

2021-08-04 14:26 UTC, tkachuk09 commented on resourse.tf
> +  public_key = file("/home/vlad/Desktop/london_region_key_pair.pub")
+

2021-08-04 14:27 UTC, tkachuk09 commented on resourse.tf
> +  public_key = file("/home/vlad/Desktop/london_region_key_pair.pub")
+

2021-08-04 14:32 UTC, tkachuk09 commented on vpc.tf
> +resource "aws_route_table_association" "public_subnet_route_table_association" {
will be done soon

2021-08-09 10:54 UTC, kteneta commented on vpc.tf
> +resource "aws_nat_gateway" "gateway" {
you don't seem to use this nat resource anywhere

2021-08-09 10:55 UTC, kteneta commented on vpc.tf
> +    gateway_id = aws_internet_gateway.gateway.id
i am not sure if it's fine that you're adding igw to private route table

2021-08-13 10:03 UTC, merged